version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://vulkyra:secretpassword@db:5432/vulkyra?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/tmp # needed for air
      # (optional) - ~/.ssh:/root/.ssh:ro if you need private repo access

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: vulkyra
      POSTGRES_USER: vulkyra
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
